export const FETCH_COUNTS_REQUEST="FETCH_COUNTS_REQUEST";
export const FETCH_COUNTS_FAILURE="FETCH_COUNTS_FAILURE";
export const FETCH_COUNTS_SUCCESS="FETCH_COUNTS_SUCCESS";
export const POST_ONE_COUNT_SUCCESS="POST_ONE_COUNT_SUCCESS";
export const POST_ONE_COUNT_FAILURE="POST_ONE_COUNT_FAILURE";
export const DELETE_ONE_COUNT_SUCCESS="DELETE_ONE_COUNT_SUCCESS";
export const DELETE_ONE_COUNT_FAILURE="DELETE_ONE_COUNT_FAILURE";
export const EDIT_ONE_COUNT_SUCCESS="EDIT_ONE_COUNT_SUCCESS";
export const EDIT_ONE_COUNT_FAILURE="EDIT_ONE_COUNT_FAILURE";

export enum ActionType{
    FETCH_COUNTS_REQUEST="FETCH_COUNTS_REQUEST",
    FETCH_COUNTS_FAILURE="FETCH_COUNTS_FAILURE",
    FETCH_COUNTS_SUCCESS="FETCH_COUNTS_SUCCESS",
    POST_ONE_COUNT_SUCCESS="POST_ONE_COUNT_SUCCESS",
    POST_ONE_COUNT_FAILURE="POST_ONE_COUNT_FAILURE",
    DELETE_ONE_COUNT_SUCCESS="DELETE_ONE_COUNT_SUCCESS",
    DELETE_ONE_COUNT_FAILURE="DELETE_ONE_COUNT_FAILURE",
    EDIT_ONE_COUNT_SUCCESS="EDIT_ONE_COUNT_SUCCESS",
    EDIT_ONE_COUNT_FAILURE="EDIT_ONE_COUNT_FAILURE",
}