export enum ActionType{
    FETCH_TODOS_REQUEST="FETCH_TODOS_REQUEST",
    FETCH_TODOS_FAILURE="FETCH_TODOS_FAILURE",
    FETCH_TODOS_SUCCESS="FETCH_TODOS_SUCCESS",
    POST_ONE_TODO_SUCCESS="POST_ONE_TODO_SUCCESS",
    POST_ONE_TODO_FAILURE="POST_ONE_TODO_FAILURE",
    DELETE_ONE_TODO_SUCCESS="DELETE_ONE_TODO_SUCCESS",
    DELETE_ONE_TODO_FAILURE="DELETE_ONE_TODO_FAILURE",
    EDIT_ONE_TODO_SUCCESS="EDIT_ONE_TODO_SUCCESS",
    EDIT_ONE_TODO_FAILURE="EDIT_ONE_TODO_FAILURE",
    FILTER_TODOS="FILTER_TODOS",
}